-- AmbuIntake database schema for Supabase / Postgres.
-- Generated by `npm run db:export-sql` — do not edit by hand.
--
-- Run this first in Supabase → SQL Editor, then run seed.sql.
-- Safe to run more than once. Everything is created in the "ambuintake" schema,
-- with row-level security on and no access for the anon/authenticated roles.

BEGIN;

CREATE SCHEMA IF NOT EXISTS ambuintake;

CREATE TABLE IF NOT EXISTS ambuintake.questions (
  id SERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  text TEXT NOT NULL,
  guidance TEXT DEFAULT '',
  answer_type TEXT NOT NULL DEFAULT 'yes_no',
  options TEXT DEFAULT '[]',
  call_types TEXT DEFAULT '[]',
  payers TEXT DEFAULT '[]',
  criterion TEXT NOT NULL DEFAULT 'info',
  qualifying_answer TEXT,
  triggers TEXT DEFAULT '[]',
  detect_yes TEXT DEFAULT '[]',
  detect_no TEXT DEFAULT '[]',
  depends_on_code TEXT,
  depends_on_answer TEXT,
  priority INTEGER NOT NULL DEFAULT 3,
  sort_order INTEGER NOT NULL DEFAULT 0,
  required BOOLEAN NOT NULL DEFAULT false,
  alert_answer TEXT,
  alert_text TEXT,
  alert_level TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  necessity BOOLEAN NOT NULL DEFAULT true,
  is_system BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS ambuintake.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ambuintake.users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'call_taker')),
  password_hash TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  must_change_password BOOLEAN NOT NULL DEFAULT false,
  last_login_at TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON ambuintake.users (lower(username));

CREATE TABLE IF NOT EXISTS ambuintake.sessions (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES ambuintake.users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS ambuintake.login_attempts (
  username TEXT PRIMARY KEY,
  failures INTEGER NOT NULL DEFAULT 0,
  locked_until BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ambuintake.payers (
  id SERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'payer',
  parent_code TEXT,
  description TEXT NOT NULL DEFAULT '',
  requires_medical_necessity BOOLEAN NOT NULL DEFAULT true,
  prior_auth TEXT NOT NULL DEFAULT '{}',
  prior_auth_note TEXT NOT NULL DEFAULT '',
  certification TEXT NOT NULL DEFAULT '',
  documentation TEXT NOT NULL DEFAULT '[]',
  alternate_transport TEXT NOT NULL DEFAULT '',
  contact_name TEXT NOT NULL DEFAULT '',
  contact_phone TEXT NOT NULL DEFAULT '',
  contact_fax TEXT NOT NULL DEFAULT '',
  contact_email TEXT NOT NULL DEFAULT '',
  contact_url TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT true,
  is_system BOOLEAN NOT NULL DEFAULT false,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
  updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS ambuintake.calls (
  id SERIAL PRIMARY KEY,
  call_type TEXT NOT NULL,
  payer TEXT,
  details TEXT NOT NULL DEFAULT '{}',
  answers TEXT NOT NULL DEFAULT '{}',
  transcript TEXT NOT NULL DEFAULT '',
  assessment TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL,
  level_of_service TEXT,
  call_taker TEXT,
  user_id INTEGER REFERENCES ambuintake.users(id),
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS ambuintake.audit_log (
  id SERIAL PRIMARY KEY,
  created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS.MS'),
  user_id INTEGER,
  username TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details TEXT NOT NULL DEFAULT '{}',
  ip TEXT
);
CREATE INDEX IF NOT EXISTS audit_log_created ON ambuintake.audit_log (created_at);
CREATE INDEX IF NOT EXISTS audit_log_user ON ambuintake.audit_log (user_id);

-- The audit trail is append-only.
CREATE OR REPLACE FUNCTION ambuintake.audit_log_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
  BEGIN RAISE EXCEPTION 'audit_log is append-only'; END $$;
DROP TRIGGER IF EXISTS audit_log_append_only ON ambuintake.audit_log;
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON ambuintake.audit_log
  FOR EACH ROW EXECUTE FUNCTION ambuintake.audit_log_append_only();

-- Keep Supabase's public API keys out (the server connects as the owner).
ALTER TABLE ambuintake.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.payers ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambuintake.audit_log ENABLE ROW LEVEL SECURITY;
DO $$
DECLARE r TEXT;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA ambuintake FROM %I', r);
      EXECUTE format('REVOKE ALL ON SCHEMA ambuintake FROM %I', r);
    END IF;
  END LOOP;
END $$;

COMMIT;
