-- AmbuIntake built-in content: settings, 6 payer profiles, 41 questions.
-- Generated by `npm run db:export-sql` — do not edit by hand.
--
-- Run after schema.sql. Safe to run more than once: existing rows are kept.
-- User accounts are not included; the first administrator is created when the
-- app starts (ADMIN_USERNAME / ADMIN_PASSWORD) or by `npm run db:setup`.

BEGIN;

-- Settings (seed_version last, so the app knows setup is complete)
INSERT INTO ambuintake.settings (key, value)
VALUES ('ai_auto_analyze', 'true')
ON CONFLICT (key) DO NOTHING;

INSERT INTO ambuintake.settings (key, value)
VALUES ('ai_enabled', 'true')
ON CONFLICT (key) DO NOTHING;

INSERT INTO ambuintake.settings (key, value)
VALUES ('org_name', 'Your Ambulance Service')
ON CONFLICT (key) DO NOTHING;

INSERT INTO ambuintake.settings (key, value)
VALUES ('seed_version', '3')
ON CONFLICT (key) DO NOTHING;

-- Payer profiles
INSERT INTO ambuintake.payers (code, name, kind, parent_code, description, requires_medical_necessity, prior_auth, prior_auth_note, certification, documentation, alternate_transport, contact_name, contact_phone, contact_fax, contact_email, contact_url, sort_order, active, is_system)
VALUES ('medicare', 'Original Medicare (Part B)', 'payer', NULL, 'Fee-for-service Medicare. Coverage criteria: 42 CFR 410.40 and Medicare Benefit Policy Manual, Ch. 10.', true, '{"emergency":"not_required","non_emergency":"not_required","repetitive":"varies"}', 'Repetitive, scheduled non-emergent transports may be subject to CMS prior authorization depending on your Medicare Administrative Contractor (MAC). Check your MAC.', 'Physician Certification Statement (PCS). Repetitive scheduled transports: signed and dated no earlier than 60 days before the transport. Non-repetitive transports: may be obtained up to 48 hours after the transport.', '["Bed-confinement alone is not sufficient — document the specific condition that makes other transport unsafe.","If the patient requests a non-emergency transport that is expected to be denied, issue an Advance Beneficiary Notice of Noncoverage (ABN) before transport."]', 'Original Medicare does not cover wheelchair-van or other non-ambulance transport. Check for Medicaid or other secondary coverage.', 'Medicare Administrative Contractor (MAC)', '', '', '', '', 10, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.payers (code, name, kind, parent_code, description, requires_medical_necessity, prior_auth, prior_auth_note, certification, documentation, alternate_transport, contact_name, contact_phone, contact_fax, contact_email, contact_url, sort_order, active, is_system)
VALUES ('medicare_advantage', 'Medicare Advantage (Part C)', 'payer', NULL, 'Private Medicare plans. Plans must cover ambulance services that Original Medicare covers and follow its coverage criteria (42 CFR 422.101), but may require prior authorization for non-emergency transport.', true, '{"emergency":"not_required","non_emergency":"varies","repetitive":"varies"}', 'Medicare Advantage plans may not require prior authorization for emergency services (42 CFR 422.113). Most plans require it for scheduled non-emergency transport — check the plan.', 'Plan-specific. Document medical necessity as for Original Medicare; most plans also require or accept a PCS.', '["Verify eligibility and the plan name using the member ID card or the plan portal.","Record the plan''s authorization or reference number on the trip.","Out-of-network non-emergency transport may not be covered unless the plan authorizes it."]', 'Many Medicare Advantage plans offer a supplemental transportation benefit (e.g., wheelchair van or rideshare). Refer the caller to the plan''s member services.', 'Plan utilization management (number on member ID card)', '', '', '', '', 20, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.payers (code, name, kind, parent_code, description, requires_medical_necessity, prior_auth, prior_auth_note, certification, documentation, alternate_transport, contact_name, contact_phone, contact_fax, contact_email, contact_url, sort_order, active, is_system)
VALUES ('medicaid', 'Medicaid', 'payer', NULL, 'State Medicaid program (fee-for-service or managed care). Coverage, forms and authorization rules are set by each state — review this profile against your state''s provider manual.', true, '{"emergency":"not_required","non_emergency":"varies","repetitive":"varies"}', 'Most states require prior authorization for non-emergency ambulance transport. Managed-care (MCO) members follow the MCO''s authorization process.', 'State-specific. Most states require a practitioner certification or medical-necessity form for non-emergency ambulance — use your state''s form.', '["Verify Medicaid eligibility for the date of service.","Medicaid is the payer of last resort: if the patient has Medicare or other coverage, bill that payer first."]', 'Medicaid must ensure necessary transportation to covered services (42 CFR 431.53). If ambulance is not indicated, refer the caller to the state''s non-emergency medical transportation (NEMT) broker for wheelchair or ambulatory transport.', 'State Medicaid / NEMT broker', '', '', '', '', 30, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.payers (code, name, kind, parent_code, description, requires_medical_necessity, prior_auth, prior_auth_note, certification, documentation, alternate_transport, contact_name, contact_phone, contact_fax, contact_email, contact_url, sort_order, active, is_system)
VALUES ('commercial', 'Commercial insurance', 'payer', NULL, 'Employer or individual health plans. Coverage criteria and authorization rules are set by each plan''s medical policy.', true, '{"emergency":"not_required","non_emergency":"varies","repetitive":"varies"}', 'Check the plan''s medical policy for non-emergency ambulance authorization requirements.', 'Plan-specific — check the plan''s medical policy.', '["Verify eligibility, benefits, and network status.","Federal No Surprises Act balance-billing protections do not apply to ground ambulance; some states have their own protections."]', 'Check whether the plan covers wheelchair-van or other non-emergency transportation.', 'Plan provider services (number on member ID card)', '', '', '', '', 40, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.payers (code, name, kind, parent_code, description, requires_medical_necessity, prior_auth, prior_auth_note, certification, documentation, alternate_transport, contact_name, contact_phone, contact_fax, contact_email, contact_url, sort_order, active, is_system)
VALUES ('private_pay', 'Private pay (self-pay)', 'payer', NULL, 'The patient or a family member pays directly. No medical-necessity review is required.', false, '{"emergency":"not_required","non_emergency":"not_required","repetitive":"not_required"}', '', '', '["Quote the transport rate and confirm the payment method before scheduling.","Have the patient or responsible party sign the financial responsibility agreement."]', '', '', '', '', '', '', 50, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.payers (code, name, kind, parent_code, description, requires_medical_necessity, prior_auth, prior_auth_note, certification, documentation, alternate_transport, contact_name, contact_phone, contact_fax, contact_email, contact_url, sort_order, active, is_system)
VALUES ('facility_pay', 'Facility pay', 'payer', NULL, 'The sending or receiving facility (hospital, SNF, hospice) pays under its agreement with us. No medical-necessity review is required.', false, '{"emergency":"not_required","non_emergency":"not_required","repetitive":"not_required"}', '', '', '["Confirm the facility has an active billing agreement with us.","Record who at the facility authorized the transport and any purchase-order number."]', '', '', '', '', '', '', 60, true, true)
ON CONFLICT (code) DO NOTHING;

-- Question bank
INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('EMG_SCREEN', 'Emergency Screening', 'Is the patient having chest pain, trouble breathing, stroke symptoms, severe bleeding, a seizure, or are they unresponsive right now?', 'Screen every call for an active emergency before continuing with a scheduled-transport intake.', 'yes_no', '[]', '[]', '[]', 'emergency', 'yes', '[]', '["chest pain","can''t breathe","cannot breathe","trouble breathing","difficulty breathing","not breathing","stroke symptoms","slurred speech","facial droop","severe bleeding","bleeding heavily","seizing","having a seizure","unresponsive","passed out"]', '["stable","no distress","resting comfortably","vitals are stable"]', NULL, NULL, 1, 10, true, 'yes', 'Possible emergency: transfer to 911 / emergency dispatch per protocol.', 'critical', true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('TX_REASON', 'Transport Details', 'What is the reason for transport and the patient''s primary diagnosis?', 'Document the condition that makes ambulance transport necessary — not just the destination appointment.', 'text', '[]', '[]', '[]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 20, true, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('TX_DEST_TYPE', 'Transport Details', 'What type of facility is the patient going to?', 'Covered destinations include hospitals, critical access hospitals, SNFs, the beneficiary''s home, and dialysis facilities for ESRD patients. Physician offices are generally not covered destinations.', 'choice', '["Hospital — emergency / inpatient","Hospital — outpatient / diagnostic","Skilled nursing facility","Patient residence","Dialysis facility","Physician office / clinic","Other"]', '[]', '[]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 30, true, 'Physician office / clinic', 'Physician offices are generally not a covered ambulance destination under Medicare.', 'warning', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('TX_NEAREST', 'Transport Details', 'Is the destination the nearest appropriate facility that can provide the care the patient needs?', 'Medicare covers mileage only to the nearest appropriate facility. If farther, document why closer facilities cannot provide the care.', 'yes_no', '[]', '[]', '[]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 2, 40, false, 'no', 'Destination is not the nearest appropriate facility — excess mileage may be non-covered. Document the reason.', 'warning', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('TX_REPETITIVE', 'Transport Details', 'Will the patient need 3 or more round trips in 10 days, or at least one trip a week for 3 weeks or more (e.g., dialysis, wound care, chemotherapy)?', 'Repetitive, scheduled non-emergent transports require a PCS dated no earlier than 60 days before the transport and may require prior authorization.', 'yes_no', '[]', '["non_emergency","repetitive"]', '[]', 'info', NULL, '[]', '["dialysis","three times a week","3 times a week","every week","weekly","monday wednesday friday","chemotherapy","chemo","radiation therapy","wound care"]', '["one time","one-time","just this once","single trip"]', NULL, NULL, 2, 50, false, 'yes', 'Repetitive transport: PCS must be dated within 60 days prior; check prior-authorization requirements.', 'info', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('TX_OTHER_MEANS', 'Transport Details', 'Could the patient safely travel by any other means (wheelchair van, car, taxi) without endangering their health?', 'Ambulance transport is covered only when other means of transportation are contraindicated by the patient''s condition.', 'yes_no', '[]', '[]', '[]', 'disqualifier', 'yes', '[]', '["wheelchair van","rides in a car","can ride in a car","family can drive","family could drive","take a taxi","takes a taxi","by car"]', '["too unstable","cannot ride in a car","can''t ride in a car","needs a stretcher","needs stretcher","must be on a stretcher"]', NULL, NULL, 1, 60, true, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('TX_CONVENIENCE', 'Transport Details', 'Is the ambulance being requested mainly because no other transportation is available, or for convenience?', 'Lack of other transportation or patient/family preference does not establish medical necessity.', 'yes_no', '[]', '[]', '[]', 'disqualifier', 'yes', '[]', '["no ride","no transportation","doesn''t have a ride","does not have a ride","no one to drive","nobody to drive","for convenience","family is not available"]', '[]', NULL, NULL, 2, 70, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('BED_GET_UP', 'Bed Confinement', 'Is the patient unable to get up from bed without assistance?', 'CMS bed-confinement test (1 of 3). All three criteria must be met for the patient to be considered bed-confined.', 'yes_no', '[]', '[]', '[]', 'bed_confined', 'yes', '[]', '["can''t get out of bed","cannot get out of bed","unable to get out of bed","needs help getting out of bed","bedbound","bed bound","bed-bound","bed confined","bed-confined","bedridden","total assist","two person assist","2 person assist","hoyer","mechanical lift"]', '["gets out of bed on","gets up on her own","gets up on his own","gets up by herself","gets up by himself","independent transfers","transfers independently"]', NULL, NULL, 2, 80, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('BED_AMBULATE', 'Bed Confinement', 'Is the patient unable to walk (ambulate)?', 'CMS bed-confinement test (2 of 3).', 'yes_no', '[]', '[]', '[]', 'bed_confined', 'yes', '[]', '["can''t walk","cannot walk","unable to walk","not able to walk","non-ambulatory","nonambulatory","doesn''t walk","does not walk","bedbound","bed bound","bed-bound","bedridden","paralyzed","paraplegic","quadriplegic"]', '["can walk","walks with","ambulatory","ambulates","walks independently","uses a walker","uses a cane"]', NULL, NULL, 2, 90, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('BED_SIT', 'Bed Confinement', 'Is the patient unable to sit in a chair or wheelchair, including for the length of the trip?', 'CMS bed-confinement test (3 of 3). A patient who can sit in a wheelchair generally does not meet this criterion.', 'yes_no', '[]', '[]', '[]', 'bed_confined', 'yes', '[]', '["can''t sit","cannot sit","unable to sit","not able to sit","can''t tolerate sitting","cannot tolerate sitting","must lie flat","must remain flat","bedbound","bed bound","bed-bound","bedridden"]', '["sits in a wheelchair","sits in wheelchair","sits in a chair","sits up in a chair","in a wheelchair","uses a wheelchair","wheelchair bound","wheelchair-bound"]', NULL, NULL, 2, 100, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_OXYGEN', 'Clinical Condition', 'Does the patient need oxygen during transport that they cannot manage or self-administer?', 'Oxygen alone may not justify ambulance transport if the patient manages their own portable oxygen. Document the need for administration or monitoring.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["on oxygen","on o2","home oxygen","home o2","nasal cannula","non-rebreather","liters of oxygen","liters oxygen","liters o2","l of oxygen","lpm","oxygen tank","needs oxygen","requires oxygen","oxygen dependent"]', '["room air","portable concentrator"]', NULL, NULL, 2, 110, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_IV', 'Clinical Condition', 'Does the patient have IV fluids or medications running that must be maintained during transport?', 'A saline-locked IV alone does not establish necessity; running fluids or medications that require monitoring do.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["iv fluids","iv drip","on a drip","iv antibiotics","infusion","running iv","iv running"]', '["saline lock","hep lock","no iv"]', NULL, NULL, 2, 120, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_DRIPS', 'Clinical Condition', 'Are there medication drips that need titration or critical-care monitoring (e.g., vasopressors, cardiac or heparin drips)?', 'Care beyond the scope of an EMT-Paramedic indicates Specialty Care Transport (SCT).', 'yes_no', '[]', '[]', '[]', 'sct', 'yes', '["drip","titrat","pressor","levophed","heparin","cardizem","diltiazem","nitro","amiodarone","insulin drip","critical care","icu"]', '["titrating","titrated","heparin drip","cardizem drip","diltiazem drip","nitro drip","nitroglycerin drip","levophed","pressors","vasopressor","insulin drip","amiodarone drip","dopamine drip"]', '[]', NULL, NULL, 2, 130, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_CARDIAC', 'Clinical Condition', 'Does the patient require cardiac monitoring during transport?', 'Cardiac monitoring is an ALS-level intervention.', 'yes_no', '[]', '[]', '[]', 'als', 'yes', '[]', '["cardiac monitor","on a monitor","telemetry","on tele","heart monitor","ekg monitoring","cardiac monitoring"]', '[]', NULL, NULL, 2, 140, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_VENT', 'Clinical Condition', 'Is the patient intubated or on a ventilator?', 'Ventilator management during transport generally requires Specialty Care Transport.', 'yes_no', '[]', '[]', '[]', 'sct', 'yes', '[]', '["ventilator","vent dependent","on the vent","on a vent","intubated"]', '[]', NULL, NULL, 2, 150, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_AIRWAY', 'Clinical Condition', 'Does the patient need airway care or suctioning during transport (e.g., tracheostomy)?', 'Airway monitoring or suctioning by trained personnel supports ambulance transport.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["trach","tracheostomy","suction","suctioning","secretions"]', '[]', NULL, NULL, 2, 160, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_LOC', 'Clinical Condition', 'Is the patient unconscious or have an altered level of consciousness requiring monitoring?', 'Document level of consciousness (e.g., responds only to voice or pain).', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["unconscious","unresponsive","obtunded","altered mental status","lethargic","comatose","not responsive","responds only to pain"]', '["alert and oriented","a&o","a and o","awake and talking"]', NULL, NULL, 2, 170, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_BEHAVIOR', 'Clinical Condition', 'Is the patient a danger to themselves or others, or do they need restraints (physical or chemical) for transport?', 'Document the behavior and the type of restraint ordered.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["restraints","restrained","combative","violent","suicidal","danger to self","danger to others","psych hold","involuntary hold","5150","baker act"]', '["calm","cooperative"]', NULL, NULL, 2, 180, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_FRACTURE', 'Clinical Condition', 'Does the patient have a fracture or an orthopedic device (traction, immobilizer, spinal precautions) that requires stretcher positioning?', 'Note the location of the fracture and how it prevents seated transport.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["fracture","fractured","broken hip","broken leg","broken pelvis","hip fx","traction","immobilizer","spinal precautions","c-collar","cervical collar"]', '[]', NULL, NULL, 2, 190, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_CONTRACTURES', 'Clinical Condition', 'Does the patient have contractures or another condition that prevents safe positioning in a seat?', 'Describe which limbs are affected and why seated positioning is unsafe.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["contracture","contractures","contracted"]', '[]', NULL, NULL, 3, 200, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_WOUNDS', 'Clinical Condition', 'Does the patient have pressure ulcers or wounds (e.g., stage 3–4 sacral/buttock wounds) that prevent sitting?', 'Document the stage and location of the wound.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["decubitus","pressure ulcer","pressure sore","pressure injury","bedsore","bed sore","sacral wound","stage 3","stage 4","stage iii","stage iv","wound vac"]', '[]', NULL, NULL, 3, 210, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_PAIN', 'Clinical Condition', 'Does the patient have severe pain that worsens with sitting or movement and requires stretcher transport?', 'Document the pain severity and what makes it worse.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["severe pain","excruciating","pain with movement","pain when moved","pain when moving","screams when moved"]', '[]', NULL, NULL, 3, 220, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_ISOLATION', 'Clinical Condition', 'Does the patient require isolation precautions (e.g., MRSA, C. diff, VRE, TB) during transport?', 'Document the organism and type of precautions.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["isolation","mrsa","c diff","c. diff","cdiff","vre","tuberculosis","contact precautions","airborne precautions","droplet precautions"]', '[]', NULL, NULL, 3, 230, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_BARIATRIC', 'Clinical Condition', 'Does the patient''s weight or size require extra personnel or bariatric equipment to move them safely?', 'Document the patient''s weight and the equipment/personnel needed.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["bariatric","morbidly obese","morbid obesity","400 pounds","500 pounds","600 pounds","400 lbs","500 lbs","600 lbs"]', '[]', NULL, NULL, 3, 240, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('CLN_MONITORING', 'Clinical Condition', 'Does the patient need monitoring by trained medical personnel during transport (e.g., unstable vital signs, post-procedure)?', 'Describe what must be monitored and why.', 'yes_no', '[]', '[]', '[]', 'condition', 'yes', '[]', '["unstable vitals","unstable vital signs","hypotensive","low blood pressure","post-op","post op","post-procedure","still sedated"]', '[]', NULL, NULL, 3, 250, false, NULL, NULL, NULL, true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('DOC_INPATIENT', 'Documentation', 'Is the patient currently a hospital inpatient or in a Medicare Part A–covered SNF stay?', 'During a covered inpatient or SNF Part A stay, transport may be the facility''s financial responsibility.', 'yes_no', '[]', '["non_emergency","repetitive"]', '["medicare","medicare_advantage"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 2, 260, false, 'yes', 'Patient is in a covered stay — the facility may be the responsible billing party. Verify before scheduling.', 'warning', true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('DOC_PCS', 'Documentation', 'Will a signed Physician Certification Statement (PCS) be provided for this transport?', 'Repetitive scheduled transports need a PCS dated no earlier than 60 days before transport. For non-repetitive transports, the certification may be obtained within 48 hours after transport.', 'yes_no', '[]', '["non_emergency","repetitive"]', '["medicare","medicare_advantage"]', 'documentation', 'yes', '[]', '[]', '[]', NULL, NULL, 1, 270, true, 'no', 'No PCS — non-emergency transport may be denied without physician certification.', 'warning', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('DOC_CERTIFIER', 'Documentation', 'Who is the certifying physician or practitioner (name and NPI)?', 'If the physician is unavailable, a PA, NP, CNS, RN, or discharge planner with knowledge of the patient''s condition may sign.', 'text', '[]', '["non_emergency","repetitive"]', '[]', 'info', NULL, '[]', '[]', '[]', 'DOC_PCS', 'yes', 3, 280, false, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('DOC_PRIOR_AUTH', 'Payer & Authorization', 'What is the status of the payer''s prior authorization for this transport?', 'Asked when the selected payer requires — or may require — prior authorization for this type of call. See the payer panel for who to contact.', 'choice', '["Approved","Not required — confirmed with payer","Pending","Denied"]', '[]', '[]', 'prior_auth', 'Approved|Not required — confirmed with payer', '[]', '[]', '[]', NULL, NULL, 2, 290, false, 'Denied', 'Prior authorization was denied — do not schedule as a covered transport. Discuss an appeal or alternate transport with the caller.', 'critical', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('DOC_AUTH_NUMBER', 'Payer & Authorization', 'What is the authorization or reference number?', 'Record it exactly as issued; it is required on the claim.', 'text', '[]', '[]', '[]', 'info', NULL, '[]', '[]', '[]', 'DOC_PRIOR_AUTH', 'Approved', 2, 300, false, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('MA_PLAN', 'Payer & Authorization', 'Which Medicare Advantage plan is the patient enrolled in?', 'Use the plan name on the member ID card. Each plan sets its own authorization process.', 'text', '[]', '[]', '["medicare_advantage"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 310, true, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('MA_NETWORK', 'Payer & Authorization', 'Is our service in-network with the patient''s Medicare Advantage plan?', 'Plans must cover emergency ambulance regardless of network, but out-of-network non-emergency transport may not be covered.', 'yes_no', '[]', '["non_emergency","repetitive"]', '["medicare_advantage"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 2, 320, false, 'no', 'Out of network: confirm the plan will authorize this non-emergency transport before scheduling.', 'warning', true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('MCD_ELIGIBILITY', 'Payer & Authorization', 'Has Medicaid eligibility been verified for the date of service?', 'Check the state eligibility system. Coverage can lapse month to month.', 'yes_no', '[]', '[]', '["medicaid"]', 'documentation', 'yes', '[]', '[]', '[]', NULL, NULL, 1, 330, true, 'no', 'Medicaid eligibility not verified — confirm coverage for the date of service before scheduling.', 'warning', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('MCD_DUAL', 'Payer & Authorization', 'Does the patient also have Medicare (dual-eligible)?', 'Medicaid is the payer of last resort.', 'yes_no', '[]', '[]', '["medicaid"]', 'info', NULL, '[]', '["dual eligible","dual-eligible","medicare and medicaid","medi-medi"]', '[]', NULL, NULL, 2, 340, false, 'yes', 'Dual-eligible: Medicare (or the Medicare Advantage plan) is primary — apply Medicare criteria and bill it first.', 'info', true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('MCD_MCO', 'Payer & Authorization', 'Is the patient enrolled in a Medicaid managed-care plan (MCO)?', 'Managed-care members follow the MCO''s authorization and transportation rules rather than fee-for-service Medicaid.', 'yes_no', '[]', '[]', '["medicaid"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 2, 350, false, 'yes', 'Medicaid managed care: get authorization from the MCO and record the MCO name with the trip.', 'info', true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('MCD_CERT', 'Payer & Authorization', 'Will the ordering practitioner complete the state''s medical-necessity / certification form?', 'Most states require a signed certification for non-emergency ambulance transport.', 'yes_no', '[]', '["non_emergency","repetitive"]', '["medicaid"]', 'documentation', 'yes', '[]', '[]', '[]', NULL, NULL, 1, 360, true, 'no', 'No certification form — the state may deny non-emergency transport without it.', 'warning', true, true, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('BRK_TRIP_NUMBER', 'Payer & Authorization', 'What is the broker''s trip or authorization number?', 'Brokers pay only for trips they assigned. Record the number exactly as issued.', 'text', '[]', '[]', '["@broker"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 370, true, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('PP_RESPONSIBLE', 'Payer & Authorization', 'Who is responsible for payment (name, relationship, and phone)?', 'Collect billing contact details before scheduling.', 'text', '[]', '[]', '["private_pay"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 380, true, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('PP_AGREED', 'Payer & Authorization', 'Has the responsible party agreed to the quoted rate and payment method?', 'Quote the rate for the requested level of service and mileage.', 'yes_no', '[]', '[]', '["private_pay"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 390, true, 'no', 'Payment not agreed — do not schedule until the rate and payment method are confirmed.', 'warning', true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('FP_AUTHORIZED_BY', 'Payer & Authorization', 'Which facility is paying, and who authorized the transport (name and title)?', 'The facility must have a billing agreement with us.', 'text', '[]', '[]', '["facility_pay"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 1, 400, true, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ambuintake.questions (code, category, text, guidance, answer_type, options, call_types, payers, criterion, qualifying_answer, triggers, detect_yes, detect_no, depends_on_code, depends_on_answer, priority, sort_order, required, alert_answer, alert_text, alert_level, active, necessity, is_system)
VALUES ('FP_PO_NUMBER', 'Payer & Authorization', 'Is there a facility purchase-order or authorization number?', 'Record it if the facility uses one.', 'text', '[]', '[]', '["facility_pay"]', 'info', NULL, '[]', '[]', '[]', NULL, NULL, 2, 410, false, NULL, NULL, NULL, true, false, true)
ON CONFLICT (code) DO NOTHING;

COMMIT;
