// Writes the database as plain SQL files for Supabase's SQL Editor:
//   supabase/schema.sql - schema, tables, append-only audit trigger, row-level security
//   supabase/seed.sql   - default settings, payer profiles and the question bank
//
//   npm run db:export-sql
//
// The files are generated from the same definitions the app uses, so running
// them gives exactly the database the app would create on its own.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDb, SCHEMA_SQL } from './db.js';

const S = 'ambuintake';
const SKIP_COLUMNS = new Set(['id', 'created_at', 'updated_at']);

const literal = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

const dedent = (sql) => sql.split('\n').map((l) => l.replace(/^ {2}/, '')).join('\n').trim();

function inserts(table, rows, conflictKey) {
  return rows.map((row) => {
    const cols = Object.keys(row).filter((c) => !SKIP_COLUMNS.has(c));
    return `INSERT INTO ${S}.${table} (${cols.join(', ')})\nVALUES (${cols.map((c) => literal(row[c])).join(', ')})\nON CONFLICT (${conflictKey}) DO NOTHING;`;
  }).join('\n\n');
}

export async function buildSqlFiles() {
  const db = await openDb({ memory: true });
  try {
    const settings = await db.query(`SELECT key, value FROM ${S}.settings ORDER BY key = 'seed_version', key`);
    const payers = await db.query(`SELECT * FROM ${S}.payers ORDER BY sort_order, code`);
    const questions = await db.query(`SELECT * FROM ${S}.questions ORDER BY sort_order, code`);

    const schema = `-- AmbuIntake database schema for Supabase / Postgres.
-- Generated by \`npm run db:export-sql\` — do not edit by hand.
--
-- Run this first in Supabase → SQL Editor, then run seed.sql.
-- Safe to run more than once. Everything is created in the "${S}" schema,
-- with row-level security on and no access for the anon/authenticated roles.

BEGIN;

${dedent(SCHEMA_SQL)}

COMMIT;
`;

    const seed = `-- AmbuIntake built-in content: settings, ${payers.length} payer profiles, ${questions.length} questions.
-- Generated by \`npm run db:export-sql\` — do not edit by hand.
--
-- Run after schema.sql. Safe to run more than once: existing rows are kept.
-- User accounts are not included; the first administrator is created when the
-- app starts (ADMIN_USERNAME / ADMIN_PASSWORD) or by \`npm run db:setup\`.

BEGIN;

-- Settings (seed_version last, so the app knows setup is complete)
${inserts('settings', settings, 'key')}

-- Payer profiles
${inserts('payers', payers, 'code')}

-- Question bank
${inserts('questions', questions, 'code')}

COMMIT;
`;
    return { schema, seed };
  } finally {
    await db.close();
  }
}

// CLI
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const outDir = path.resolve(process.argv[2] || 'supabase');
  fs.mkdirSync(outDir, { recursive: true });
  const { schema, seed } = await buildSqlFiles();
  fs.writeFileSync(path.join(outDir, 'schema.sql'), schema);
  fs.writeFileSync(path.join(outDir, 'seed.sql'), seed);
  console.log(`Wrote ${path.join(outDir, 'schema.sql')} and ${path.join(outDir, 'seed.sql')}`);
}
